import type { DocumentTemplateDefinition } from "@/types/document-template";

export const DOCUMENT_REGISTRY: DocumentTemplateDefinition[] = [
  // ----------------------------------------------------
  // 1. [보호자 소통 - 5종] (category: "guardian")
  // ----------------------------------------------------
  {
    id: "doc_01",
    category: "guardian",
    categoryLabel: "보호자 소통",
    title: "1. 보호자 일일 알림장",
    description: "어르신의 오늘 식사, 투약, 특이사항, 프로그램 참여 모습을 담은 일일 알림장입니다.",
    requiredBlocks: ["guardian_message", "meal_hydration", "common_program"],
    optionalBlocks: ["individual_participation", "special_notes"],
    excludedBlocks: ["health_vitals", "elimination"],
    allowedVisibilityScopes: ["guardian_ok", "auto_doc_ok", "promo_ok"],
    audience: "guardian",
    targetAudienceLabel: "보호자 (카카오톡/알림장)",
    tone: "warm",
    targetLength: "medium",
    actions: ["send_kakao", "send_sms", "save", "export_pdf"],
    hwpxTemplateName: "guardian_daily_notice.hwpx"
  },
  {
    id: "doc_02",
    category: "guardian",
    categoryLabel: "보호자 소통",
    title: "2. 보호자 문자 요약",
    description: "핵심 생활 및 케어 내용만 요약한 90자 단문 LMS 문자 메시지입니다.",
    requiredBlocks: ["guardian_message"],
    optionalBlocks: ["attendance_transport", "meal_hydration"],
    excludedBlocks: ["health_vitals", "elimination", "actions_taken"],
    allowedVisibilityScopes: ["guardian_ok", "auto_doc_ok"],
    audience: "guardian",
    targetAudienceLabel: "보호자 (SMS/LMS)",
    tone: "concise",
    targetLength: "short",
    actions: ["send_sms", "save"],
    hwpxTemplateName: "guardian_sms_summary.hwpx"
  },
  {
    id: "doc_03",
    category: "guardian",
    categoryLabel: "보호자 소통",
    title: "3. 카카오 알림톡 문안",
    description: "카카오톡 브랜드 알림톡 전용 템플릿 서식 문안입니다.",
    requiredBlocks: ["attendance_transport", "guardian_message"],
    optionalBlocks: ["meal_hydration", "common_program"],
    excludedBlocks: ["health_vitals", "elimination"],
    allowedVisibilityScopes: ["guardian_ok", "auto_doc_ok"],
    audience: "guardian",
    targetAudienceLabel: "보호자 (카카오 알림톡)",
    tone: "warm",
    targetLength: "short",
    actions: ["send_kakao", "save"],
    hwpxTemplateName: "kakao_alimtalk.hwpx"
  },
  {
    id: "doc_04",
    category: "guardian",
    categoryLabel: "보호자 소통",
    title: "4. 보호자 상담 후속 안내문",
    description: "생활 관찰 및 건강 특이사항에 기반한 보호자 정기 상담 안내서입니다.",
    requiredBlocks: ["special_notes", "guardian_message"],
    optionalBlocks: ["actions_taken", "individual_participation"],
    excludedBlocks: ["health_vitals", "elimination"],
    allowedVisibilityScopes: ["guardian_ok", "auto_doc_ok"],
    audience: "guardian",
    targetAudienceLabel: "보호자 (서면/모바일)",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf", "send_kakao"],
    hwpxTemplateName: "counseling_followup.hwpx"
  },
  {
    id: "doc_05",
    category: "guardian",
    categoryLabel: "보호자 소통",
    title: "5. 월간 생활 요약문",
    description: "한 달간의 출석률, 건강 추이, 프로그램 반응을 종합한 월간 소식지입니다.",
    requiredBlocks: ["attendance_transport", "common_program", "individual_participation"],
    optionalBlocks: ["health_vitals", "emotion_behavior_cognition"],
    excludedBlocks: ["elimination"],
    allowedVisibilityScopes: ["guardian_ok", "auto_doc_ok"],
    audience: "guardian",
    targetAudienceLabel: "보호자 (월간 리포트)",
    tone: "warm",
    targetLength: "long",
    actions: ["save", "export_pdf", "send_kakao"],
    hwpxTemplateName: "monthly_life_summary.hwpx"
  },

  // ----------------------------------------------------
  // 2. [법정·내부 기록 - 6종] (category: "internal")
  // ----------------------------------------------------
  {
    id: "doc_06",
    category: "internal",
    categoryLabel: "법정·내부 기록",
    title: "6. 장기요양급여 제공기록 문안",
    description: "국민건강보험공단 장기요양 고시 서식에 맞춘 장기요양급여 제공기록 표준 문안입니다.",
    requiredBlocks: ["attendance_transport", "health_vitals", "meal_hydration", "medication", "elimination"],
    optionalBlocks: ["common_program", "individual_participation", "actions_taken"],
    excludedBlocks: [],
    allowedVisibilityScopes: ["internal_only", "auto_doc_ok", "guardian_ok"],
    audience: "staff",
    targetAudienceLabel: "국민건강보험공단 / 평가용",
    tone: "formal_legal",
    targetLength: "long",
    actions: ["save", "export_pdf", "export_hwpx"],
    hwpxTemplateName: "longterm_care_record.hwpx"
  },
  {
    id: "doc_07",
    category: "internal",
    categoryLabel: "법정·내부 기록",
    title: "7. 일일 종합 관찰기록",
    description: "어르신의 신체·정서·행동·인지 반응을 종합 관찰한 서면 일일 보고서입니다.",
    requiredBlocks: ["emotion_behavior_cognition", "individual_participation"],
    optionalBlocks: ["health_vitals", "rest_sleep", "special_notes"],
    excludedBlocks: [],
    allowedVisibilityScopes: ["internal_only", "auto_doc_ok"],
    audience: "staff",
    targetAudienceLabel: "내부 요양보호사/사회복지사",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "daily_observation_record.hwpx"
  },
  {
    id: "doc_08",
    category: "internal",
    categoryLabel: "법정·내부 기록",
    title: "8. 건강·투약·바이탈 특이사항 보고서",
    description: "간호팀 및 시설장에 보고하는 건강 이상 및 투약 특이사항 보고서입니다.",
    requiredBlocks: ["health_vitals", "medication", "actions_taken"],
    optionalBlocks: ["special_notes"],
    excludedBlocks: [],
    allowedVisibilityScopes: ["internal_only"],
    audience: "manager",
    targetAudienceLabel: "시설장 / 간호팀장",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "health_vitals_report.hwpx"
  },
  {
    id: "doc_09",
    category: "internal",
    categoryLabel: "법정·내부 기록",
    title: "9. 프로그램 참여 및 반응 기록지",
    description: "개별 수급자의 프로그램 수행능력 및 수혜 상태를 수치·문장 기록한 서식입니다.",
    requiredBlocks: ["common_program", "individual_participation"],
    optionalBlocks: ["emotion_behavior_cognition"],
    excludedBlocks: ["elimination", "medication"],
    allowedVisibilityScopes: ["internal_only", "auto_doc_ok"],
    audience: "staff",
    targetAudienceLabel: "프로그램 담당 사회복지사",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "program_reaction_record.hwpx"
  },
  {
    id: "doc_10",
    category: "internal",
    categoryLabel: "법정·내부 기록",
    title: "10. 사회복지사 일일 업무일지",
    description: "오늘의 수급자 관리, 케어 조치, 외부 외근 및 프로그램 총괄 일지입니다.",
    requiredBlocks: ["attendance_transport", "common_program", "special_notes", "actions_taken"],
    optionalBlocks: ["guardian_message"],
    excludedBlocks: [],
    allowedVisibilityScopes: ["internal_only", "auto_doc_ok"],
    audience: "manager",
    targetAudienceLabel: "시설장 결재용",
    tone: "formal_legal",
    targetLength: "long",
    actions: ["save", "export_pdf", "export_hwpx"],
    hwpxTemplateName: "social_worker_daily_log.hwpx"
  },
  {
    id: "doc_11",
    category: "internal",
    categoryLabel: "법정·내부 기록",
    title: "11. 야간/교대 직원 인수인계서",
    description: "다음 교대 근무 직원에게 전달하는 수급자별 주시사항 및 필수 인수인계서입니다.",
    requiredBlocks: ["medication", "special_notes", "actions_taken"],
    optionalBlocks: ["health_vitals", "rest_sleep"],
    excludedBlocks: [],
    allowedVisibilityScopes: ["internal_only"],
    audience: "staff",
    targetAudienceLabel: "야간/교대 근무 직원",
    tone: "concise",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "staff_shift_handover.hwpx"
  },

  // ----------------------------------------------------
  // 3. [프로그램 문서 - 4종] (category: "program")
  // ----------------------------------------------------
  {
    id: "doc_12",
    category: "program",
    categoryLabel: "프로그램 문서",
    title: "12. 프로그램 운영 결과기록서",
    description: "오늘 실시한 인지·신체 프로그램의 종합 성과 및 수급자 반응 결과서입니다.",
    requiredBlocks: ["common_program", "individual_participation"],
    optionalBlocks: ["emotion_behavior_cognition"],
    excludedBlocks: ["health_vitals", "elimination"],
    allowedVisibilityScopes: ["auto_doc_ok", "internal_only"],
    audience: "manager",
    targetAudienceLabel: "프로그램 개발팀 / 관리자",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "program_result_report.hwpx"
  },
  {
    id: "doc_13",
    category: "program",
    categoryLabel: "프로그램 문서",
    title: "13. 프로그램 종합 평가 및 개선안",
    description: "프로그램 난이도, 참여율, 정서적 만족도를 분석하여 다음 회기를 개선하는 보고서입니다.",
    requiredBlocks: ["common_program", "individual_participation"],
    optionalBlocks: ["emotion_behavior_cognition", "special_notes"],
    excludedBlocks: ["elimination", "medication"],
    allowedVisibilityScopes: ["auto_doc_ok", "internal_only"],
    audience: "manager",
    targetAudienceLabel: "평가위원회 / 사회복지사",
    tone: "formal_legal",
    targetLength: "long",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "program_evaluation_improvement.hwpx"
  },
  {
    id: "doc_14",
    category: "program",
    categoryLabel: "프로그램 문서",
    title: "14. 다음 회기 프로그램 기안서",
    description: "오늘의 반응 및 참여도를 바탕으로 기획하는 차주 프로그램 기안 및 계획서입니다.",
    requiredBlocks: ["common_program"],
    optionalBlocks: ["individual_participation", "special_notes"],
    excludedBlocks: ["health_vitals", "elimination"],
    allowedVisibilityScopes: ["auto_doc_ok", "internal_only"],
    audience: "manager",
    targetAudienceLabel: "센터장 결재용 기안서",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf", "export_hwpx"],
    hwpxTemplateName: "next_session_proposal.hwpx"
  },
  {
    id: "doc_15",
    category: "program",
    categoryLabel: "프로그램 문서",
    title: "15. 개별 어르신 참여평가서",
    description: "수급자 개별 맞춤형 인지 기능 변화 및 신체 프로그램 참여도 단독 평가서입니다.",
    requiredBlocks: ["individual_participation", "emotion_behavior_cognition"],
    optionalBlocks: ["common_program", "special_notes"],
    excludedBlocks: ["elimination"],
    allowedVisibilityScopes: ["auto_doc_ok", "internal_only", "guardian_ok"],
    audience: "staff",
    targetAudienceLabel: "담당 사회복지사 / 보호자 참고용",
    tone: "warm",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "individual_participation_eval.hwpx"
  },

  // ----------------------------------------------------
  // 4. [홍보·운영 - 5종] (category: "operation")
  // ----------------------------------------------------
  {
    id: "doc_16",
    category: "operation",
    categoryLabel: "홍보·운영",
    title: "16. 가정통신문 및 안내장",
    description: "센터 월간 행사, 식단표, 감염병 예방수칙 등을 안내하는 가정통신문입니다.",
    requiredBlocks: ["common_program"],
    optionalBlocks: ["guardian_message"],
    excludedBlocks: ["health_vitals", "elimination", "medication", "special_notes"],
    allowedVisibilityScopes: ["promo_ok", "auto_doc_ok", "guardian_ok"],
    audience: "public",
    targetAudienceLabel: "전체 이용자 보호자",
    tone: "warm",
    targetLength: "medium",
    actions: ["publish", "save", "export_pdf"],
    hwpxTemplateName: "center_newsletter_home.hwpx"
  },
  {
    id: "doc_17",
    category: "operation",
    categoryLabel: "홍보·운영",
    title: "17. 블로그 프로그램 후기 글",
    description: "네이버 블로그 및 기관 웹사이트 홍보용 생생한 활동 후기 포스팅입니다.",
    requiredBlocks: ["common_program"],
    optionalBlocks: ["individual_participation"],
    excludedBlocks: ["health_vitals", "elimination", "medication", "special_notes"],
    allowedVisibilityScopes: ["promo_ok", "consent_needed"],
    audience: "public",
    targetAudienceLabel: "지역 주민 / 마케팅 채널",
    tone: "promo",
    targetLength: "long",
    actions: ["publish", "save"],
    hwpxTemplateName: "blog_program_review.hwpx"
  },
  {
    id: "doc_18",
    category: "operation",
    categoryLabel: "홍보·운영",
    title: "18. 인스타그램 카드뉴스 문안",
    description: "인스타그램 1:1 이미지 카드뉴스 슬라이드에 들어갈 감성적인 짧은 문안입니다.",
    requiredBlocks: ["common_program"],
    optionalBlocks: [],
    excludedBlocks: ["health_vitals", "elimination", "medication", "special_notes"],
    allowedVisibilityScopes: ["promo_ok"],
    audience: "public",
    targetAudienceLabel: "인스타그램 / SNS 구독자",
    tone: "promo",
    targetLength: "short",
    actions: ["publish", "save"],
    hwpxTemplateName: "instagram_card_news.hwpx"
  },
  {
    id: "doc_19",
    category: "operation",
    categoryLabel: "홍보·운영",
    title: "19. 월간 소식지 기사 원고",
    description: "기관 소식지 및 인쇄물에 실릴 이번 달 어르신 활동 종합 기사 원고입니다.",
    requiredBlocks: ["common_program", "individual_participation"],
    optionalBlocks: [],
    excludedBlocks: ["health_vitals", "elimination", "medication", "special_notes"],
    allowedVisibilityScopes: ["promo_ok", "auto_doc_ok"],
    audience: "public",
    targetAudienceLabel: "월간 소식지 구독자",
    tone: "promo",
    targetLength: "long",
    actions: ["publish", "save", "export_pdf"],
    hwpxTemplateName: "monthly_journal_article.hwpx"
  },
  {
    id: "doc_20",
    category: "operation",
    categoryLabel: "홍보·운영",
    title: "20. 직원 내부 교육 자료",
    description: "오늘의 수급자 케어 특이사항 및 조치 사례를 반영한 직무 교육 및 케어 가이드입니다.",
    requiredBlocks: ["special_notes", "actions_taken"],
    optionalBlocks: ["emotion_behavior_cognition"],
    excludedBlocks: ["elimination"],
    allowedVisibilityScopes: ["internal_only", "auto_doc_ok"],
    audience: "staff",
    targetAudienceLabel: "요양보호사 / 신입 직원 교육",
    tone: "formal_legal",
    targetLength: "medium",
    actions: ["save", "export_pdf"],
    hwpxTemplateName: "staff_training_guide.hwpx"
  }
];

export function getTemplateById(id: string): DocumentTemplateDefinition | undefined {
  return DOCUMENT_REGISTRY.find((d) => d.id === id);
}

export function getTemplatesByCategory(
  category: DocumentTemplateDefinition["category"]
): DocumentTemplateDefinition[] {
  return DOCUMENT_REGISTRY.filter((d) => d.category === category);
}
